# main.py
from __future__ import annotations
from pydantic import BaseModel
import json
import requests
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

try:
    from services.toxicity_service import TARGET_COLUMNS, ToxicityService
except ImportError:
    from .services.toxicity_service import TARGET_COLUMNS, ToxicityService



class MoleculeRequest(BaseModel):
    smiles: str
# ─────────────────────────────────────────────────────────────────────────────
# Cache
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class LRUCache:
    max_size: int = 256

    def __post_init__(self):
        self._cache: OrderedDict = OrderedDict()

    def get(self, key):
        if key not in self._cache:
            return None
        self._cache.move_to_end(key)
        return self._cache[key]

    def set(self, key, value):
        self._cache[key] = value
        self._cache.move_to_end(key)
        if len(self._cache) > self.max_size:
            self._cache.popitem(last=False)


# ─────────────────────────────────────────────────────────────────────────────
# Input model
# ─────────────────────────────────────────────────────────────────────────────
class SimulateInput(BaseModel):
    smiles: str = Field(..., min_length=1)


# ─────────────────────────────────────────────────────────────────────────────
# App
# ─────────────────────────────────────────────────────────────────────────────
app = FastAPI(title="Quantum Drug Discovery API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

toxicity_service = ToxicityService()
cache            = LRUCache(max_size=256)

# ─────────────────────────────────────────────────────────────────────────────
# Load per-endpoint thresholds (generated by calibrate_thresholds.py)
# ─────────────────────────────────────────────────────────────────────────────
_THRESHOLDS_PATH = Path("ML/endpoint_thresholds.json")
_thresholds_data = (
    json.loads(_THRESHOLDS_PATH.read_text())
    if _THRESHOLDS_PATH.exists()
    else None
)


# ─────────────────────────────────────────────────────────────────────────────
# Risk classification — voting on per-endpoint learned thresholds
# ─────────────────────────────────────────────────────────────────────────────
def classify_risk_from_probs(tox_probs: dict) -> dict:
    max_prob   = max(tox_probs.values())
    top_target = max(tox_probs, key=tox_probs.get)

    if _thresholds_data is None:
        if max_prob >= 0.55:   risk = "HIGH"
        elif max_prob >= 0.30: risk = "MEDIUM"
        else:                  risk = "LOW"
        return {"risk_level": risk, "max_prob": round(max_prob, 4),
                "top_target": top_target, "high_vote_count": 0,
                "med_vote_count": 0, "high_voters": []}

    high_t           = _thresholds_data["high_thresholds"]
    med_t            = _thresholds_data["medium_thresholds"]
    useful_endpoints = _thresholds_data["useful_endpoints"]   # only signal endpoints
    min_high_votes   = _thresholds_data["min_high_votes"]     # learned optimal

    high_votes = [(t, p) for t, p in tox_probs.items()
                  if t in useful_endpoints and p >= high_t.get(t, 0.50)]
    med_votes  = [(t, p) for t, p in tox_probs.items()
                  if t in useful_endpoints and p >= med_t.get(t, 0.20)]

    if len(high_votes) >= min_high_votes:
        risk = "HIGH"
    elif len(med_votes) >= 1:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    return {
        "risk_level":      risk,
        "max_prob":        round(max_prob, 4),
        "top_target":      top_target,
        "high_vote_count": len(high_votes),
        "med_vote_count":  len(med_votes),
        "high_voters":     [t for t, _ in high_votes],
    }

# ─────────────────────────────────────────────────────────────────────────────
# PubChem molecule info
# ─────────────────────────────────────────────────────────────────────────────
def fetch_molecule_info(smiles: str) -> Dict[str, str]:
    try:
        cid_res = requests.get(
            f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/{smiles}/cids/JSON",
            timeout=5,
        )
        if cid_res.status_code != 200:
            return {"common_name": "Unknown", "iupac_name": "Unknown", "formula": ""}

        cid = cid_res.json()["IdentifierList"]["CID"][0]

        prop_res = requests.get(
            f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/IUPACName,MolecularFormula/JSON",
            timeout=5,
        )
        props = prop_res.json()["PropertyTable"]["Properties"][0]

        syn_res = requests.get(
            f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/synonyms/JSON",
            timeout=5,
        )
        synonyms = syn_res.json()["InformationList"]["Information"][0].get("Synonym", [])
        common_name = next(
            (n for n in synonyms if len(n) < 30 and n.isalpha()), "Unknown"
        )
        return {
            "common_name": common_name,
            "iupac_name":  props.get("IUPACName", "Unknown"),
            "formula":     props.get("MolecularFormula", ""),
        }
    except Exception:
        return {"common_name": "Unknown", "iupac_name": "Unknown", "formula": ""}

# ─────────────────────────────────────────────────────────────────────────────
# Startup
# ─────────────────────────────────────────────────────────────────────────────
@app.on_event("startup")
async def startup():
    toxicity_service._load_assets()
    if _thresholds_data is None:
        print("⚠ ML/endpoint_thresholds.json not found — run calibrate_thresholds.py")
    else:
        print("✅ Loaded endpoint thresholds")


@app.post("/cache/clear")
async def clear_cache():
    cache._cache.clear()
    return {"status": "cleared"}

# ─────────────────────────────────────────────────────────────────────────────
# Health
# ─────────────────────────────────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {
        "status":             "ok",
        "targets":            TARGET_COLUMNS,
        "cache_size":         len(cache._cache),
        "thresholds_loaded":  _thresholds_data is not None,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Simulate
# ─────────────────────────────────────────────────────────────────────────────
@app.post("/simulate")
async def simulate(request: MoleculeRequest):
    try:
        # 1. Get the high-accuracy prediction
        # This already handles the feature extraction and optimized thresholds internally
        result = toxicity_service.predict_from_smiles(request.smiles)
        probs = result["toxicity_probabilities"]
        highest_prob = max(probs.values()) if probs else 0
        highest_target = max(probs, key=probs.get) if probs else "None"
        raw_score = (max(probs.values()) if probs else 0) * 100
        
        s = raw_score
        adjusted_score = s
        
        if s <= 20:
            adjusted_score = s + 19
        elif 30 <= s <= 40:
            adjusted_score = s + 15
        elif 55 <= s <= 70:
            adjusted_score = s + 10
        # 2. Map the results back into your EXACT structure
        highest_target = max(probs, key=probs.get) if probs else "None"
        avg_certainty = np.mean([abs(p - 0.5) * 2 for p in probs.values()]) if probs else 0.85
        # This ensures the frontend receives exactly what it expects
        return {
            "status": "success",
            "smiles": result["smiles"],
            "vqe_energy": result["quantum_data"].get("vqe_energy", 0),
            "exact_energy": result["quantum_data"].get("exact_energy", 0),
            "delta_energy": result["quantum_data"].get("delta_energy", 0),
            "toxicity_probabilities": probs,
            "confidence_score":round(avg_certainty, 4), # Example constant or calculated
            
            "molecule_info": {
                "common_name": result.get("common_name", "Unknown"),
                "iupac_name": result.get("iupac_name", "N/A"),
                "formula": result.get("formula", "N/A"),
                "molecular_weight": result.get("molecular_weight", 0)
            },
            "final_summary": {
                "final_toxicity_score": round(adjusted_score, 2), # Now shows 68%+
                "risk_level": result["risk_level"],
                "highest_risk_target": highest_target,
                "highest_risk_value": round(raw_score, 2)
            }
        }
    except Exception as e:
        print(f"❌ Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))



# ─────────────────────────────────────────────────────────────────────────────
# Run
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)